name: CI/CD Pipeline

on:
  push:

jobs:
  first_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go # installs go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: run # causes a download of the dependencies
        run: go run .

  second_run:
    runs-on: ubuntu-latest
    needs: first_run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go # reuses the cached installation
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: run # reuses the cached dependencies
        run: go run .
